config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  devise_scope :user do
    get 'shipping_addresses', to: 'users/registrations#new_shipping_address'
    post 'shipping_addresses', to: 'users/registrations#create_shipping_address'
  end
  root 'shops#index'
  resources :shops, only: :index
  post 'items/new', to:'items#create'
  patch 'items/:id/edit', to: 'items#update'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
      get 'search'
      get 'detail_search'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end
    resource :order, only: [:new,:create] do
      collection do
        get 'done', to: 'orders#done'
      end
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :categories, only: [:index, :show]
  resources :brands, only: [:index,:show]
  resources :shipping_addresses
  resources :credit_cards, only: [:index, :new, :show, :create,:destroy]
  resources :users, only: :show do
    collection do
      get :likes
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  validates :nickname, presence: true
  validates :last_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :birth_day, presence: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }, length: { minimum: 7 }
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true

  has_many :sns_credentials
  has_one :shipping_address
  has_many :items, dependent: :destroy
  has_one :credit_card
  has_many :order
  has_many :likes, dependent: :destroy
  has_many :liked_items, through: :likes, source: :item
  has_many :comments, dependent: :destroy

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  def failure
    redirect_to root_path
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def new
    @user = User.new
  end

  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @shipping_address = @user.build_shipping_address
    render :new_shipping_address
  end

  def create_shipping_address
    @user = User.new(session["devise.regist_data"]["user"])
    @shipping_address = ShippingAddress.new(shipping_address_params)
    unless @shipping_address.valid?
      flash.now[:alert] = @shipping_address.errors.full_messages
      render :new_shipping_address and return
    end
    @user.build_shipping_address(@shipping_address.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
  end

  protected

  def shipping_address_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :zipcode, :prefecture, :city, :address, :building, :phone_number)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @brands = Brand.all
    @category_parents = Category.all.where(ancestry: nil)
  end

  def likes
    @brands = Brand.all
    @category_parents = Category.all.where(ancestry: nil)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_side-bar.html.haml
.left-content
  %nav.nav
    %ul.nav__list
      %li.nav__list__box
        = link_to user_path(current_user.id), class: "nav__list__box--item active" do
          マイページ
          = icon('fas', 'angle-right', class: "nav__list__box--item--icon")
      %li.nav__list__box
        = link_to likes_users_path, class: "nav__list__box--item active", id: "like_index" do
          いいね！一覧
          = icon('fas', 'angle-right', class: "nav__list__box--item--icon")
      %li.nav__list__box
        = link_to new_item_path, class: "nav__list__box--item active" do
          出品する
          = icon('fas', 'angle-right', class: "nav__list__box--item--icon")
      %li.nav__list__box
        = link_to "#", class: "nav__list__box--item active" do
          出品した商品-出品中
          = icon('fas', 'angle-right', class: "nav__list__box--item--icon")
      %li.nav__list__box
        = link_to "#", class: "nav__list__box--item active" do
          出品した商品-取引中
          = icon('fas', 'angle-right', class: "nav__list__box--item--icon")
      %li.nav__list__box
        = link_to "#", class: "nav__list__box--item active" do
          出品した商品-売却済み
          = icon('fas', 'angle-right', class: "nav__list__box--item--icon")
      %li.nav__list__box
        = link_to "#", class: "nav__list__box--item active" do
          購入した商品-取引中
          = icon('fas', 'angle-right', class: "nav__list__box--item--icon")
      %li.nav__list__box
        = link_to "#", class: "nav__list__box--item active" do
          購入した商品-過去の取引
          = icon('fas', 'angle-right', class: "nav__list__box--item--icon")
      %li.nav__list__box
        = link_to "#", class: "nav__list__box--item active" do
          評価一覧
          = icon('fas', 'angle-right', class: "nav__list__box--item--icon")
    %h3.nav__title 設定
    %ul.nav__list
      %li.nav__list__box
        = link_to "#", class: "nav__list__box--item active" do
          プロフィール
          = icon('fas', 'angle-right', class: "nav__list__box--item--icon")
      %li.nav__list__box
        = link_to "#", class: "nav__list__box--item active" do
          発送元・お届け先住所変更
          = icon('fas', 'angle-right', class: "nav__list__box--item--icon")
      %li.nav__list__box
        = link_to credit_cards_path, class: "nav__list__box--item active" do
          支払い方法
          = icon('fas', 'angle-right', class: "nav__list__box--item--icon")
      %li.nav__list__box
        = link_to "#", class: "nav__list__box--item active" do
          メール/パスワード
          = icon('fas', 'angle-right', class: "nav__list__box--item--icon")
      %li.nav__list__box
        = link_to "#", class: "nav__list__box--item active" do
          本人情報
          = icon('fas', 'angle-right', class: "nav__list__box--item--icon")
      %li.nav__list__box
        = link_to "#", class: "nav__list__box--item active" do
          電話番号の確認
          = icon('fas', 'angle-right', class: "nav__list__box--item--icon")
      %li.nav__list__box
        = link_to destroy_user_session_path, class: "nav__list__box--item active", method: :delete do
          %span ログアウト
          = icon('fas', 'angle-right', class: "nav__list__box--item--icon")

app/views/users/_user-info.html.haml
.mypage-user
  = link_to "#", class: "mypage-user__link" do
    %figure
      = image_tag("/images/member_photo_noimage_thumb.png", alt: "member", class: "member", width: "60", height: "60")
    %h2.nickname
      = current_user.nickname
    .mypage-count
      .mypage-count__evaluation
        評価
        %span.mypage-count__evaluation--number 10
      .mypage-count__exhibition
        出品数
        %span.mypage-count__exhibition--number 30

app/views/users/likes.html.haml
.header-main
  = render partial: "/layouts/main_header"

.bread-crumb
  %ul.bread-crumb__nav
    %li.bread-crumb__nav__item
      = link_to root_path, class: "bread-crumb__nav__item--link" do
        %span フリマ
      = icon('fas', 'chevron-right', class: "bread-crumb__nav__item--icon")
      = link_to user_path(current_user.id), class: "bread-crumb__nav__item--link present-location" do
        %span マイページ

.mypage-main
  = render "side-bar"
  .right-content
    = render "user-info"
    .mypage-tab-container
      %h2.mypage-tab-head いいね一覧
      .like-content
        %ul.like-lists
          - current_user.liked_items.each do |item|
            %li
              = link_to item_path(item.id), class: "sammary" do
                .item-image
                  = image_tag item.images[0].image.url, alt: "sample", class: "sample"
                .caption
                  = item.name
                  %br
                  = number_to_currency(item.price,format: "%u%n", unit: "¥")
                = icon('fas', 'angle-right', class: "nav__list__box--item--icon")

%aside.banner-for-app
  .banner-inner
    %h2.banner-inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.banner-inner__text
      今すぐ無料ダウンロード！
    .inner-icons
      = link_to image_tag("/images/appstore-icon.png",alt:"appstore",class:"icon-image"),"#",class:"icon-left"
      = link_to image_tag("/images/googlestore-icon.png",alt:"googleplay",class:"icon-image"),"#",class:"icon-right"

.main-footer
  = render partial: "/layouts/main-footer"

= link_to new_item_path do
  .sell-btn
    %span.sell-btn__text 出品
    = image_tag("/images/icon_camera.png", alt: "CAMERA", class: "sell-btn__image")

app/views/users/show.html.haml
.header-main
  = render partial: "/layouts/main_header"

- breadcrumb :mypage
= render "/layouts/bread-crumbs"

.mypage-main
  = render "side-bar"
  .right-content
    = render "user-info"
    .mypage-tab-container
      %h2.mypage-tab-head 購入した商品
      .tabs
        = radio_button_tag(:tab, "left", "")
        %label{for: "tab_left", class: "tab-item"} 取引中
        = radio_button_tag(:tab, "right")
        %label{for: "tab_right", class: "tab-item"} 過去の取引
        .tab-content#tab_left
          = image_tag("/images/logo-white.png",alt:"FURIMA",class:"logo-bottom",height:"50",width:"170")
          %p.tab-content-text 取引中の商品がありません
        .tab-content#tab_right
          = image_tag("/images/logo-white.png",alt:"FURIMA",class:"logo-bottom",height:"50",width:"170")
          %p.tab-content-text 過去に取引した商品がありません

%aside.banner-for-app
  .banner-inner
    %h2.banner-inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.banner-inner__text
      今すぐ無料ダウンロード！
    .inner-icons
      = link_to image_tag("/images/appstore-icon.png",alt:"appstore",class:"icon-image"),"#",class:"icon-left"
      = link_to image_tag("/images/googlestore-icon.png",alt:"googleplay",class:"icon-image"),"#",class:"icon-right"

.main-footer
  = render partial: "/layouts/main-footer"

= link_to new_item_path do
  .sell-btn
    %span.sell-btn__text 出品
    = image_tag("/images/icon_camera.png", alt: "CAMERA", class: "sell-btn__image")