config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  devise_scope :user do
    get 'shipping_addresses', to: 'users/registrations#new_shipping_address'
    post 'shipping_addresses', to: 'users/registrations#create_shipping_address'
  end
  root 'shops#index'
  resources :shops, only: :index
  post 'items/new', to:'items#create'
  patch 'items/:id/edit', to: 'items#update'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
      get 'search'
      get 'detail_search'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end
    resource :order, only: [:new,:create] do
      collection do
        get 'done', to: 'orders#done'
      end
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :categories, only: [:index, :show]
  resources :brands, only: [:index,:show]
  resources :shipping_addresses
  resources :credit_cards, only: [:index, :new, :show, :create,:destroy]
  resources :users, only: :show do
    collection do
      get :likes
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :item
  belongs_to :seller, class_name: 'User', optional: true, foreign_key: true
  belongs_to :buyer, class_name: 'User', optional: true, foreign_key: true

  validates :receiver_last_name, presence: true
  validates :receiver_first_name, presence: true
  validates :zipcode, presence: true
  validates :prefecture, presence: true
  validates :city, presence: true
  validates :address, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_item
  require "payjp"


  def new
    if @item.item_status == false
    @order = Order.new
    @buyer = User.find_by(id: current_user.id)
    @card = CreditCard.find_by(user_id: current_user.id)
      unless @card.nil?
        Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
      @card_brand = @default_card_information.brand
      case @card_brand
      when "Visa"
        @card_src = "logo_visa.gif"
      when "JCB"
        @card_src = "jcb-logomark-img-02.gif"
      when "MasterCard"
        @card_src = "logo_mastercard.gif"
      when "Diners Club"
        @card_src = "diners-logomark-img-01.gif"
      when "Discover"
        @card_src = "discover-logomark-img-08.gif"
      end
      end
    else
      redirect_to item_path(@item.id)
    end
  end

  def create
    @order = Order.new(order_params)
    if @item.item_status == false
      card = CreditCard.find_by(user_id: current_user.id)
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
      Payjp::Charge.create(
        amount: @item.price,
        customer: card.customer_id,
        currency: 'jpy',
      )
      @item.update(item_status: true)
      redirect_back(fallback_location: new_item_order_path(@item.id)) unless @order.save
    else
      redirect_back(fallback_location: new_item_order_path(@item.id))
    end
  end

  private
  def order_params
    params.require(:order).permit(:seller_id,:buyer_id,:item_id,:zipcode,:prefecture,:city,:address,:building,:receiver_last_name,:receiver_first_name)
  end

  def set_item
    @item = Item.find(params[:item_id])
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/create.html.haml
.header
  %h1.title-logo
    = link_to image_tag("/images/logo.png", alt:"FURIMA", class: "logo"), root_path, class: "logo-link"
    
.purchased-notice
  .greeting
    %h1.greet
      購入完了
  .notice-container
    %h2.title
      購入商品
    .item-info
      .image
        = image_tag @item.images[0].image.url,alt:"item-image",class:"image-one"
      .name
        %h3.name-title
          商品名
        %h5.name-item
          = simple_format(@item.name)
      .price
        %h3.price-title
          金額
        %h5.price-item
          = number_to_currency(@item.price,format: "%u%n",unit: "¥")
    .link
      .link-to-top
        = link_to "トップページへ",root_path,class:"linked"
      .link-to-mypage
        = link_to "マイページへ",user_path(current_user.id),class:"linked"
.footer
  = render "/layouts/form_footer"

app/views/orders/done.html.haml
.header
  %h1.title-logo
    = link_to image_tag("/images/logo.png", alt:"FURIMA", class: "logo"), root_path, class: "logo-link"
    
.purchased-notice
  .greeting
    %h1.greet
      購入完了
  .notice-container
    %h2.title
      購入商品
    .item-info
      .image
        = image_tag @item.images[0].image.url,alt:"item-image",class:"image-one"
      .name
        %h3.name-title
          商品名
        %h5.name-item
          = simple_format(@item.name)
      .price
        %h3.price-title
          金額
        %h5.price-item
          = number_to_currency(@item.price,format: "%u%n",unit: "¥")
    .link
      .link-to-top
        = link_to "トップページへ",root_path,class:"linked"
      .link-to-mypage
        = link_to "マイページへ",mypage_index_path,class:"linked"
.footer
  = render "/layouts/form_footer"

app/views/orders/new.html.haml
.header
  %h1.title-logo
    = link_to image_tag("/images/logo.png", alt:"FURIMA", class: "logo"), root_path, class: "logo-link"

.purchase-detals-main
  .main-title-container
    %h2.main-title-container__text 購入内容の確認
  .selected-item-container
    .selected-item-container__content
      .selected-item-container__content__inner
        = image_tag @item.images[0].image.url, alt:"", class: "selected-item-container__content__inner--image"
        .item-detail
          %p.item-detail--name
            = @item.name
          %p.item-detail--price
            %span
            = number_to_currency(@item.price,format:"%u%n",unit:"¥")
            %span.item-detail--price--fee （税込）送料込み
  .payment-container
    .payment-container__contents
      .payment-container__contents__inner
        %ul.price-table
          %li.price-table__label
            .price-table__label--text 支払い金額
            .price-table__label--amount
              %span
              = number_to_currency(@item.price,format:"%u%n",unit:"¥")
        - if @buyer.credit_card.present?
          .card-info
            .card-info__label
              %h3.card-info__label--text 支払い方法
              = link_to credit_cards_path(@item.user_id), class: "sipping-adress__inner__label--right" do
                %span 変更する
            .card-number
              %h3.title 
                クレジットカード
              .card-list
                .card-list-image
                  = image_tag "/images/#{@card_src}", class: "credit_card_info__brand__img", alt: @card_brand, width:"50px",height:"40px"
              %span.number
                = "**** **** **** " + @default_card_information.last4
            .expire-date 
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
              %span.expiration
                有効期限
              %span.date-year
                = exp_month + " / " + exp_year
            .sipping-adress
              .sipping-adress__inner
                .sipping-adress__inner__label.clearfix
                  %h3.sipping-adress__inner__label--left 配送先
                  = link_to "#", class: "sipping-adress__inner__label--right" do
                    %span 変更する
                %address.sipping-adress__inner--info
                  %p 
                    = @buyer.shipping_address.zipcode
                    %br/ 
                    = @buyer.shipping_address.prefecture
                    = @buyer.shipping_address.city
                    = @buyer.shipping_address.address
                    = @buyer.shipping_address.building
                    %br/ 
                    %br/ 
                    = @buyer.nickname
          = form_with(model: [@item, @order], local: true,url: item_order_path) do |f|
            = f.hidden_field :seller_id, value: @item.user.id
            = f.hidden_field :buyer_id, value: current_user.id
            = f.hidden_field :item_id, value:@item.id
            = f.hidden_field :zipcode, value: current_user.shipping_address.zipcode
            = f.hidden_field :prefecture,value: current_user.shipping_address.prefecture
            = f.hidden_field :city, value: current_user.shipping_address.city
            = f.hidden_field :address, value: current_user.shipping_address.address
            = f.hidden_field :building, value: current_user.shipping_address.building
            = f.hidden_field :receiver_last_name, value: current_user.shipping_address.last_name
            = f.hidden_field :receiver_first_name, value: current_user.shipping_address.first_name
            = f.submit "購入する",class:"hidden_form"
        - else
          .method
            .method__label
              %h3.method__label--text 支払い方法
              = link_to new_credit_card_path, class: "method__label--link" do
                = icon('fas', 'plus-circle', class: "method__label--link--icon")
                %span.method__label--link--comment 登録してください
          .sipping-adress
            .sipping-adress__inner
              .sipping-adress__inner__label.clearfix
                %h3.sipping-adress__inner__label--left 配送先
                = link_to "#", class: "sipping-adress__inner__label--right" do
                  %span 変更する
              %address.sipping-adress__inner--info
                %p 
                  = @buyer.shipping_address.zipcode
                  %br/ 
                  = @buyer.shipping_address.prefecture
                  = @buyer.shipping_address.city
                  = @buyer.shipping_address.address
                  = @buyer.shipping_address.building
                  %br/ 
                  %br/ 
                  = @buyer.nickname
          .buy-content
            %h3.alert
              支払い方法の入力を完了してください。
            %h1 購入する

.footer
  = render "/layouts/form_footer"

app/views/orders/show.html.haml
.header
  %h1.title-logo
    = link_to image_tag("/images/logo.png", alt:"FURIMA", class: "logo"), root_path, class: "logo-link"

.purchase-detals-main
  .main-title-container
    %h2.main-title-container__text 購入内容の確認
  .selected-item-container
    .selected-item-container__content
      .selected-item-container__content__inner
        = image_tag @item.images[0].image.url, alt:"", class: "selected-item-container__content__inner--image"
        .item-detail
          %p.item-detail--name
            = @item.name
          %p.item-detail--price
            %span
            = number_to_currency(@item.price,format:"%u%n",unit:"¥")
            %span.item-detail--price--fee （税込）送料込み
  .payment-container
    .payment-container__contents
      .payment-container__contents__inner
        %ul.price-table
          %li.price-table__label
            .price-table__label--text 支払い金額
            .price-table__label--amount
              %span
              = number_to_currency(@item.price,format:"%u%n",unit:"¥")
        - if @buyer.credit_card.present?
          .card-info
            .card-info__label
              %h3.card-info__label--text 支払い方法
              = link_to credit_cards_path(@item.user_id), class: "sipping-adress__inner__label--right" do
                %span 変更する
            .card-number
              %h3.title 
                クレジットカード
              %span.number
                = "**** **** **** " + @default_card_information.last4
            .expire-date 
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
              %span.expiration
                有効期限
              %span.date-year
                = exp_month + " / " + exp_year
            .sipping-adress
              .sipping-adress__inner
                .sipping-adress__inner__label.clearfix
                  %h3.sipping-adress__inner__label--left 配送先
                  = link_to "#", class: "sipping-adress__inner__label--right" do
                    %span 変更する
                %address.sipping-adress__inner--info
                  %p 
                    = @buyer.shipping_address.zipcode
                    %br/ 
                    = @buyer.shipping_address.prefecture
                    = @buyer.shipping_address.city
                    = @buyer.shipping_address.address
                    = @buyer.shipping_address.building
                    %br/ 
                    %br/ 
                    = @buyer.nickname
          .buy-content
            = form_tag(action: :pay,method: :post) do
              %button 購入する
        - else
          .method
            .method__label
              %h3.method__label--text 支払い方法
              = link_to new_credit_card_path, class: "method__label--link" do
                = icon('fas', 'plus-circle', class: "method__label--link--icon")
                %span.method__label--link--comment 登録してください
          .sipping-adress
            .sipping-adress__inner
              .sipping-adress__inner__label.clearfix
                %h3.sipping-adress__inner__label--left 配送先
                = link_to "#", class: "sipping-adress__inner__label--right" do
                  %span 変更する
              %address.sipping-adress__inner--info
                %p 
                  = @buyer.shipping_address.zipcode
                  %br/ 
                  = @buyer.shipping_address.prefecture
                  = @buyer.shipping_address.city
                  = @buyer.shipping_address.address
                  = @buyer.shipping_address.building
                  %br/ 
                  %br/ 
                  = @buyer.nickname
          .buy-content
            %h3.alert
              支払い方法の入力を完了してください。
            %h1 購入する

.footer
  = render "/layouts/form_footer"