config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  devise_scope :user do
    get 'shipping_addresses', to: 'users/registrations#new_shipping_address'
    post 'shipping_addresses', to: 'users/registrations#create_shipping_address'
  end
  root 'shops#index'
  resources :shops, only: :index
  post 'items/new', to:'items#create'
  patch 'items/:id/edit', to: 'items#update'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
      get 'search'
      get 'detail_search'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end
    resource :order, only: [:new,:create] do
      collection do
        get 'done', to: 'orders#done'
      end
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :categories, only: [:index, :show]
  resources :brands, only: [:index,:show]
  resources :shipping_addresses
  resources :credit_cards, only: [:index, :new, :show, :create,:destroy]
  resources :users, only: :show do
    collection do
      get :likes
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :user
    belongs_to :category
    belongs_to :size, optional: true
    belongs_to_active_hash :brand
    belongs_to_active_hash :ship_from_area
    belongs_to_active_hash :shipping_method
    belongs_to_active_hash :shipping_day
    belongs_to_active_hash :delivery_fee
    belongs_to_active_hash :condition
    has_many :images, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    has_one :order
  
    validates_associated :images
    validates :images, presence: true
    validates :name,
      presence: true,
      length: {maximum:40}
    validates :description,
      presence: true,
      length: {maximum:1000}
    validates :price,
      presence: true,
      numericality: {greater_than_or_equal_to:300,less_than:10000000}

    accepts_nested_attributes_for :images, allow_destroy:true

    def like_user(user_id)
      likes.find_by(user_id: user_id)
    end

    def self.search(search)
      Item.where(['name LIKE ?', "%#{search}%"])
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_item, only: [ :edit, :update, :show, :destroy]
  before_action :category_all, only: [:index, :show]
  before_action :brand_category_header, only: [:index, :show, :search, :detail_search]
  before_action :set_detail_search, only: [:index, :detail_search]

  def index
    @items = Item.includes(:user, :likes, :images).where(item_status:false).order("id DESC").page(params[:page]).per(50)
  end

  def new
    @item = Item.new
    @item.images.new
    @parents = Category.includes(:item).order("id ASC")
    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
  end

  def get_category_children
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def get_size
    selected_grandchild = Category.find("#{params[:grandchild_id]}")
    if related_size_parent = selected_grandchild.sizes[0]
      @sizes = related_size_parent.children
    else
      selected_child = Category.find("#{params[:grandchild_id]}").parent
      if related_size_parent = selected_child.sizes[0]
        @sizes = related_size_parent.children
      end
    end
  end

  def create
    @item = Item.new(item_params)
    unless @item.save
      flash.now[:alert] = "画像を入力してください"
      @item.images.new
      @category_parent_array = Category.where(ancestry: nil).pluck(:name)
      render :new
    end
  end

  def edit
    grandchild_category = @item.category
    child_category = grandchild_category.parent


    @category_parent_array = []
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end

    @category_children_array = []
    Category.where(ancestry: child_category.ancestry).each do |children|
      @category_children_array << children
    end

    @category_grandchildren_array = []
    Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
      @category_grandchildren_array << grandchildren
    end
  end

  def update
    unless @item.update(item_update_params)
      flash.now[:alert] = "更新できませんでした"

      grandchild_category = @item.category
      child_category = grandchild_category.parent

      @category_parent_array = Category.where(ancestry: nil).pluck(:name)

      @category_children_array = []
      Category.where(ancestry: child_category.ancestry).each do |children|
        @category_children_array << children
      end

      @category_grandchildren_array = []
      Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
        @category_grandchildren_array << grandchildren
      end
      render :edit
    end
  end

  def show
    @items = Item.includes(:user).where(users: {id: @item.user_id},item_status:false).limit(3)
    @categories = Item.includes(:category).where(categories: {id: @item.category_id}).limit(3)
    @comment = Comment.new
    @comments = @item.comments.order(created_at: :desc)
  end

  def destroy
    if @item.destroy
      redirect_to items_path
    else
      flash.now[:alert] = "削除できませんでした"
      render :show
    end
  end

  def search
    @search = params[:search]
    if @search == ''
      redirect_to items_path
    else
      @items = Item.search(params[:search])
    end
  end

  def detail_search
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price, :category_id, :brand_id, :size_id, :condition_id, :delivery_fee_id, :shipping_method_id, :ship_from_area_id, :shipping_day_id, :item_status, images_attributes: [:image]).merge(user_id: current_user.id)
  end

  def item_update_params
    params.require(:item).permit(:id, :name, :description, :price, :category_id, :brand_id, :size_id, :condition_id, :delivery_fee_id, :shipping_method_id, :ship_from_area_id, :shipping_day_id, :item_status, images_attributes: [:image, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def detail_search_params
    params.require(:q).permit(:sorts, :price_gteq, :price_lteq, condition_id_in: [], delivery_fee_id_in: [])
  end
  
  def set_item
    @item = Item.find(params[:id])
  end

  def brand_category_header
    @category_parents = Category.where(ancestry: nil)
    @brands = Brand.all
  end

  def category_all
    @item_category_lady = Item.includes(:category).where(item_status:0,category_id:1..199).limit(10)
    @item_category_mens = Item.includes(:category).where(item_status:0,category_id:200..345).limit(10)
    @item_category_hobby = Item.includes(:category).where(item_status:0,category_id:685..797).limit(10)
    @item_category_gadget = Item.includes(:category).where(item_status:0,category_id:898..983).limit(10)
  end

  def set_detail_search
    @q = Item.ransack(params[:q])
    @search_items = @q.result.includes(:user, :likes, :images).where(item_status: false)
  end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_detail_search_form.html.haml
= search_form_for @q, url: detail_search_items_path, class: "detail-search__form" do |f|
  = f.select( :sorts, { '並び替え': 'id desc', '価格の安い順': 'price asc', '価格の高い順': 'price desc', '出品の古い順': 'updated_at asc', '出品の新しい順': 'updated_at desc' } , { onchange: 'this.form.submit()'}, class: "detail-search__form--select" )
  %i.fas.fa-chevron-down.detail-search__form--arrow-icon
  .detail-search__form__container
    %h2.detail-search__form__container--main-title 詳細検索
    %i.fas.fa-search
    = f.label :condition_id_in, "商品の状態", class: "detail-search__form__container--sub-title"
    .detail-search__form__container--checkbox
      %input{type: "checkbox", id: "condition_all", name: "condition_all", class: "checkbox-all"}
      = label_tag :condition_all, "すべて", class: "checkbox-all-label"
      .detail-search__form__container--checkbox--select
        = f.collection_check_boxes :condition_id_in, Condition.all, :id, :name, include_hidden: false do |b|
          #boxes.detail-search__form__container--checkbox--select--boxes
            = b.check_box class: "checkbox"
            = b.label class: "checkbox-label"
    %i.fas.fa-search
    = f.label :delivery_fee_id_in, "配送料の負担", class: "detail-search__form__container--sub-title"
    .detail-search__form__container--checkbox
      %input{type: "checkbox", id: "delivery_fee_all", name: "condition_all", class: "checkbox-all"}
      = label_tag :delivery_fee_all, "すべて", class: "checkbox-all-label"
      .detail-search__form__container--checkbox--select
        = f.collection_check_boxes :delivery_fee_id_in, DeliveryFee.all, :id, :name, include_hidden: false do |b|
          #boxes.detail-search__form__container--checkbox--select--boxes
            = b.check_box class: "checkbox"
            = b.label class: "checkbox-label"
    %i.fas.fa-search
    = f.label :price, "価格", class: "detail-search__form__container--sub-title"
    .detail-search__form__container--price
      = f.number_field :price_gteq, placeholder: "¥ Min", class: "detail-search__form__container--price--input"
      .detail-search__form__container--price--range 〜
      = f.number_field :price_lteq, placeholder: "¥ Max", class: "detail-search__form__container--price--input"
    .detail-search__form--submit
      .clear-btn
        .clear#clear クリア
      .submit-btn
        = f.submit "完了", id: "submit"

app/views/items/_favorite-items-lists.html.haml
- @items.each do |item| 
  %li.items-lists__each
    .item-sammary
      = link_to item_path(item.id), class:"sammary" do
        %figure.item-image
          .image-thumbnail
            %span.price
              ¥
              = item.price.to_s(:delimited, delimiter: ',')
            = image_tag item.images[0].image.url, alt:"sample", class:"sample"
          %figcaption.caption
            %span.line
              = item.name.truncate(20)
            .like-count
              = render partial: 'likes/like_display', locals:{ item: item }

app/views/items/_favorites_item_hobby.html.haml
- @item_category_hobby.each do |item|
  %li.items-lists__each
    .item-sammary
      = link_to item_path(item.id),class:"sammary" do
        %figure.item-image
          .image-thumbnail
            %span.price
              = number_to_currency(item.price,format: "%u%n",unit: "¥")
            = image_tag item.images[0].image.url,alt:"sample",class:"sample"
          %figcaption.caption
            %span.line
              = item.name.truncate(20)
            .like-count
              = render partial: 'likes/like_display', locals:{ item: item }

app/views/items/_favorites_item_mens.html.haml
- @item_category_mens.each do |item|
  %li.items-lists__each
    .item-sammary
      = link_to item_path(item.id),class:"sammary" do
        %figure.item-image
          .image-thumbnail
            %span.price
              = number_to_currency(item.price,format: "%u%n",unit: "¥")
            = image_tag item.images[0].image.url,alt:"sample",class:"sample"
          %figcaption.caption
            %span.line
              = item.name.truncate(20)
            .like-count
              = render partial: 'likes/like_display', locals:{ item: item }

app/views/items/_other-items-lists.html.haml
.item-other-content
  %h2.item-other-title
    = link_to "#{@item.user.nickname}さんのその他の出品", "#", class: "other-item"
  .favorite-more
    = link_to "#", class: "more-items" do
      %span.item-category
        もっと見る
      = icon("fas","arrow-right")
.item-others-container
  %ul.items-lists
    - @items.each do |item|
      %li.items-lists__each
        .item-sammary
          = link_to item_path(item.id), class: "sammary" do
            %figure.item-image
              .image-thumbnail
                %span.price
                  ¥
                  = item.price.to_s(:delimited, delimiter: ',')
                = image_tag item.images[0].image.url, alt:"sample", class:"sample"
              %figcaption.caption
                %span.line
                  = item.name.truncate(20)
                .like-count
                  = render partial: 'likes/like_display', locals:{ item: item }

.item-other-content
  %h2.item-other-title
    = link_to "#{@item.category.root.name}のそのほかの商品", category_path(@item.category.root_id), class: "other-item"
  .favorite-more
    = link_to category_path(@item.category.root_id), class: "more-items" do
      %span.item-category
        もっと見る
      = icon("fas","arrow-right")
.item-others-container
  %ul.items-lists
    - @categories.each do |item|
      %li.items-lists__each
        .item-sammary
          = link_to item_path(item.id), class: "sammary" do
            %figure.item-image
              .image-thumbnail
                %span.price
                  ¥
                  = item.price.to_s(:delimited, delimiter: ',')
                = image_tag item.images[0].image.url, alt:"sample", class:"sample"
              %figcaption.caption
                %span.line
                  = item.name.truncate(20)
                .like-count
                  = render partial: 'likes/like_display', locals:{ item: item }

app/views/items/_slider-item-image.html.haml
%ul#slider
  - if @item.images.count == 1
    %li.slide-item
      = image_tag @item.images[0].image.url, alt: "image", class: "slide-image"
  - else
    - @item.images[0...5].each do |image|
      %li.slide-item
        = image_tag image.image.url, alt: "image", class: "slide-image"

%ul#thumbnail-list
  - if @item.images.count >= 2
    - @item.images[0...5].each do |image|
      %li.thumbnail-item
        = image_tag image.image.url, alt: "image", class: "thumbnail-image"

app/views/items/create.html.haml
.header
  %h1.title-logo
    = link_to image_tag("/images/logo.png", alt:"FURIMA", class:"logo"), root_path, class:"logo-link"

.create-main
  .sign-up-container
    %h2.sign-up-container__title 商品出品が完了しました
    .create_user
      .submit-contents
        .actions
          = link_to "トップページへ戻る", root_path, class: "return"
          = link_to "さらに商品を出品する", new_item_path, class: "return"

app/views/items/detail_search.html.haml
.header-main
  = render partial:'/layouts/main_header'

- breadcrumb :item_all
= render "/layouts/bread-crumbs"

.main-screen
  .detail-search
    = render "detail_search_form"
  .main-box
    .items-genre-box
      %h2.box-title
        検索結果
    .favorite-container
      .favorite-title-box-top
        %h3.favorite-title
          = @search_items.count
          %span 件検索
      .items-boxes
        %ul.items-lists
          - @search_items.each do |item|
            %li.items-lists__each
              .item-sammary
                = link_to item_path(item.id), class: "sammary" do
                  %figure.item-image
                    .image-thumbnail
                      %span.price
                        = number_to_currency(item.price,format: "%u%n", unit: "¥")
                      = image_tag item.images[0].image.url, alt: "sample", class: "sample"
                    %figcaption.caption
                      %span.line
                        = item.name.truncate(22)
                      .like-count
                        = render partial: 'likes/like_display', locals:{ item: item }
.main-footer
  = render partial:"/layouts/main-footer"

app/views/items/index.html.haml
.header-main
  = render partial:'/layouts/main_header'

- breadcrumb :item_all
= render "/layouts/bread-crumbs"

.main-screen
  .detail-search
    = render "detail_search_form"
  .main-box
    .items-genre-box
      %h2.box-title
        新着商品
    .favorite-container
      .favorite-title-box-else
        %h3.favorite-title
          新着アイテム
      .items-boxes
        %ul.items-lists
          = render partial:"/items/item.all"
    .items-genre-box
      %h2.box-title
        人気のカテゴリー
      .genre-famous
        %ul.genre-lists
          %li.genre-lists__list
            = link_to "レディース",category_path(1),class:"list"
          %li.genre-lists__list
            = link_to "メンズ",category_path(200),class:"list"
          %li.genre-lists__list
            = link_to "家電・スマホ・カメラ",category_path(898),class:"list"
          %li.genre-lists__list
            = link_to "おもちゃ・ホビー・グッズ",category_path(685),class:"list"
    .favorite-container
      .favorite-title-box-else
        %h3.favorite-title
          レディース新着アイテム
        .favorite-more
          = link_to category_path(1),class:"more-items" do
            %span.item-category
              もっと見る
            = icon("fas","arrow-right")
      .items-boxes
        %ul.items-lists
          = render partial:"/items/favorite_item_ladys"
      .favorite-title-box-else
        %h3.favorite-title
          メンズ新着アイテム
        .favorite-more
          = link_to category_path(200),class:"more-items" do
            %span.item-category
              もっと見る
            = icon("fas","arrow-right")
      .items-boxes
        %ul.items-lists
          = render partial:"/items/favorites_item_mens"
      .favorite-title-box-else
        %h3.favorite-title
          家電・スマホ・カメラ新着アイテム
        .favorite-more
          = link_to category_path(898),class:"more-items" do
            %span.item-category
              もっと見る
            = icon("fas","arrow-right")
      .items-boxes
        %ul.items-lists
          = render partial:"/items/favorite_item_gadget"
      .favorite-title-box-else
        %h3.favorite-title
          おもちゃ・ホビー・グッズ新着アイテム
        .favorite-more
          = link_to category_path(685),class:"more-items" do
            %span.item-category
              もっと見る
            = icon("fas","arrow-right")
      .items-boxes
        %ul.items-lists
          = render partial:"/items/favorites_item_hobby"

%aside.banner-for-app
  .banner-inner
    %h2.banner-inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.banner-inner__text
      今すぐ無料ダウンロード！
    .inner-icons
      = link_to image_tag("/images/appstore-icon.png",alt:"appstore",class:"icon-image"),"#",class:"icon-left"
      = link_to image_tag("/images/googlestore-icon.png",alt:"googleplay",class:"icon-image"),"#",class:"icon-right"

= link_to new_item_path do
  .sell-btn
    %span.sell-btn__text 出品
    = image_tag("/images/icon_camera.png", alt: "CAMERA", class: "sell-btn__image")

app/views/items/search.html.haml
.header-main
  = render partial: "/layouts/main_header"


.main-screen
  .main-box
    .favorite-container
      .favorite-title-box-top
        %h3.favorite-title
          = "[#{@search}]  の検索結果"
      .items-boxes
        %ul.items-lists
          - if @items.exists?
            - @items.each do |item|
              %li.items-lists__each
                .item-sammary
                  = link_to item_path(item.id), class:"sammary" do
                    %figure.item-image
                      .image-thumbnail
                        %span.price
                          = number_to_currency(item.price,format: "%u%n", unit: "¥")
                        = image_tag item.images[0].image.url, alt: "sample", class: "sample"
                      %figcaption.caption
                        %span.line
                          = item.name.truncate(22)
                        .like-count
                          = icon("far", "heart")
                          %span.item-box-likes__number
                            0
          - else
            .create-main
              .add-more-items
                %h2.notice__title 該当する商品がありません。
                .create
                  .submit-next
                    .actions
                      = link_to "トップページへ戻る", root_path, class: "return"
                      = link_to "商品を出品する", new_item_path, class: "return"

%aside.banner-for-app
  .banner-inner
    %h2.banner-inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.banner-inner__text
      今すぐ無料ダウンロード！
    .inner-icons
      = link_to image_tag("/images/appstore-icon.png",alt:"appstore",class:"icon-image"),"#",class:"icon-left"
      = link_to image_tag("/images/googlestore-icon.png",alt:"googleplay",class:"icon-image"),"#",class:"icon-right"
.main-footer
  = render partial:"/layouts/main-footer"

= link_to new_item_path do
  .sell-btn
    %span.sell-btn__text 出品
    = image_tag("/images/icon_camera.png", alt: "CAMERA", class: "sell-btn__image")

app/views/items/show.html.haml
.header-main
  = render partial:"/layouts/main_header"
.main
  %h1.main-title
    = @item.name
  .main-container
    .item-photos
      = render partial:"slider-item-image"
    %table.item-details
      %tbody.item-container
        %tr.item-details-table
          %th.item-details-table__containers
            出品者
          %td.item-details-table__information
            = link_to @item.user.nickname, "#", class:"user-name"
            .user-evaluations-container
              .user-evaluations-good
                = icon("far", "grin-beam")
                %span.user-evaluations-good__number
                  234
              .user-evaluations-normal
                = icon("far", "meh")
                %span.user-evaluations-normal__number
                  19
              .user-evaluations-bad
                = icon("far", "sad-tear")
                %span.user-evaluations-bad__number
                  345
        %tr.item-details-table
          %th.item-details-table__containers
            カテゴリー
          %td.item-details-table__information
            = link_to category_path(@item.category.root_id), class:"category" do
              = @item.category.root.name
            = link_to category_path(@item.category.parent_id), class:"category" do
              = icon("fas", "chevron-right")
              = @item.category.parent.name
            = link_to category_path(@item.category_id), class:"category" do
              = icon("fas", "chevron-right")
              = @item.category.name
        %tr.item-details-table
          %th.item-details-table__containers
            ブランド
          %td.item-details-table__information
            - if @item.brand_id?
              = link_to "#", class:"brand" do
                = @item.brand.name
        %tr.item-details-table
          %th.item-details-table__containers
            商品のサイズ
          %td.item-details-table__information
            - if @item.size_id?
              = @item.size.name
        %tr.item-details-table
          %th.item-details-table__containers
            商品の状態
          %td.item-details-table__information
            = @item.condition.name
        %tr.item-details-table
          %th.item-details-table__containers
            送料の負担
          %td.item-details-table__information
            = @item.delivery_fee.name
        %tr.item-details-table
          %th.item-details-table__containers
            発送の方法
          %td.item-details-table__information
            = @item.shipping_method.name
        %tr.item-details-table
          %th.item-details-table__containers
            発送元地域
          %td.item-details-table__information
            = @item.ship_from_area.name
        %tr.item-details-table
          %th.item-details-table__containers
            発送日の目安
          %td.item-details-table__information
            = @item.shipping_day.name
  .price-container
    %span.price-container__price
      ¥
      = @item.price.to_s(:delimited, delimiter: ',')
    %span.price-container__tax
      (税込)
    %span.price-container__shipping-fee
      = @item.delivery_fee.name

  .conditional-branch
    - if user_signed_in? && current_user.id == @item.user_id
      .edit-menu
        .edit-menu__list
          = link_to "編集", edit_item_path(@item.id), class: "edit-delete-btn"
          = link_to "削除", item_path(@item.id), method: :delete, class: "edit-delete-btn"
    - elsif user_signed_in? && current_user.id != @item.user_id
      - if @item.item_status == false
        .purchase
          = link_to "購入画面に進む", new_item_order_path(@item.id), class: "link-to-purchase"
      - else
        .purchase
          %h3.soldout
            売り切れ
    - else
      .purchase
        = link_to new_user_registration_path, class: "link-to-purchase" do
          会員登録はこちら

  .item-description
    %p.item-description__inner
      = @item.description
  .item-likes{id: "likes_buttons_#{@item.id}"}
    = render partial: 'likes/like', locals:{ item: @item }
.item-messages
  .item-messages__container
    .item-messages__container--text
      #comment-area.comment-area
        = render partial: 'comments/index', locals: { comments: @comments }
    .item-messages__container--form
      - if user_signed_in?
        .form-area
          %p.form-area__warning
            相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
          = render partial: 'comments/form', locals: { comment: @comment, item: @item }
      - else
        %p.message-warning
          商品の購入、コメントの投稿には新規会員登録/ログインが必要です
%ul.link-to-items
  %li.link-to-items__previous
    = link_to "#", class:"previous-item" do
      = icon("fas", "chevron-left")
      前の商品
  %li.link-to-items__next
    = link_to "#", class:"next-item" do
      次の商品
      = icon("fas", "chevron-right")
.item-social-medias
  .social-media-text
  %ul.social-media-container
    %li.social-media-container__box
      = link_to "#",class:"facebook" do
        = icon("fab","facebook")
    %li.social-media-container__box
      = link_to "#", class:"twitter" do
        = icon("fab","twitter")
    %li.social-media-container__box
      = link_to "#",class:"instagram" do
        = icon("fab","instagram")
.item-other-in-this-user
  = render partial:"other-items-lists"
.bottom-category-connection
  %ul.categories-box
    %li.categories-box__root
      = link_to root_path,class:"category-root" do
        %span.root-name
          メルカリ
      = icon("fas","arrow-right")
    %li.categories-box__parent
      = link_to "カテゴリー","#",class:"category-parent"
%aside.banner-for-app
  .banner-inner
    %h2.banner-inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.banner-inner__text
      今すぐ無料ダウンロード！
    .inner-icons
      = link_to image_tag("/images/appstore-icon.png",alt:"appstore",class:"icon-image"),"#",class:"icon-left"
      = link_to image_tag("/images/googlestore-icon.png",alt:"googleplay",class:"icon-image"),"#",class:"icon-right"
.main-footer
  = render partial:"/layouts/main-footer"

app/views/items/update.html.haml
.header
  %h1.title-logo
    = link_to image_tag("/images/logo.png", alt:"FURIMA", class:"logo"), root_path, class:"logo-link"

.create-main
  .sign-up-container
    %h2.sign-up-container__title 編集が完了しました
    .create_user
      .submit-contents
        .actions
          = link_to "トップページへ戻る", root_path, class: "return"
          = link_to "商品一覧ページへ戻る", items_path, class: "return"
          = link_to "商品詳細ページへ戻る", item_path(@item.id), class: "return"