config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  devise_scope :user do
    get 'shipping_addresses', to: 'users/registrations#new_shipping_address'
    post 'shipping_addresses', to: 'users/registrations#create_shipping_address'
  end
  root 'shops#index'
  resources :shops, only: :index
  post 'items/new', to:'items#create'
  patch 'items/:id/edit', to: 'items#update'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
      get 'search'
      get 'detail_search'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end
    resource :order, only: [:new,:create] do
      collection do
        get 'done', to: 'orders#done'
      end
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :categories, only: [:index, :show]
  resources :brands, only: [:index,:show]
  resources :shipping_addresses
  resources :credit_cards, only: [:index, :new, :show, :create,:destroy]
  resources :users, only: :show do
    collection do
      get :likes
    end
  end
end

app/models/brand.rb
class Brand < ActiveHash::Base
  self.data = [
    {id: 1, name:"ルイヴィトン"},{id: 2, name:"プラダ"},{id: 3, name:"バーバリー"},{id: 4, name:"シャネル"},{id: 5, name:"コーチ"},
    {id: 6, name:"アルマーニ"},{id: 7, name:"ジョーダン"},{id: 8, name:"ティファニー"},{id: 9, name:"エルメス"},{id: 10, name:"ダンヒル"},
    {id: 11, name:"ディオール"},{id: 12, name:"ブルガリ"},{id: 13, name:"カルティエ"},{id: 14, name:"カルバンクライン"},{id: 15, name:"ディーゼル"},
    {id: 16, name:"フェンディ"},{id: 17, name:"フランクミュラー"},{id: 18, name:"ミュウミュウ"},{id: 19, name:"オメガ"},{id: 20, name:"スワロフスキー"},
    {id: 21, name:"ベルサーチ"},{id: 22, name:"ロレックス"},{id: 23, name:"ナイキ"},{id: 24, name:"アディダス"},{id: 25, name:"プーマ"},
    {id: 26, name:"カッパ"},{id: 27, name:"ディアドラ"},{id: 28, name:"アンブロ"},{id: 29, name:"ユニクロ"},{id: 30, name:"ミズノ"},
    {id: 31, name:"アシックス"},{id: 32, name:"コンバース"},{id: 33, name:"コロンビア"},{id: 34, name:"パタゴニア"},{id: 35, name:"ノースフェイス"},
    {id: 36, name:"フィラ"},{id: 37, name:"ロゴス"},{id: 38, name:"チャンピオン"},{id: 39, name:"その他"}
  ]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_many :category_sizes
  has_many :sizes, through: :category_sizes
  has_ancestry

  def find_items
    if self.root?
      first_id = self.indirects.first.id
      last_id = self.indirects.last.id
      items = Item.where(category_id: first_id..last_id)
    elsif self.has_children? && self.has_parent?
      first_id = self.children.first.id
      last_id = self.children.last.id
      items = Item.where(category_id: first_id..last_id)
    else
      items = self.items
    end
  end
end

app/models/category_size.rb
class CategorySize < ApplicationRecord
  belongs_to :category
  belongs_to :size
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :item

  validates :comment, presence: true
  
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    {id: 1, name: "新品未使用"},{id: 2,name:"未使用に近い"},{id: 3, name: "目立った傷や汚れなし"},
    {id: 4, name: "やや傷や汚れあり"}, {id: 5, name: "傷や汚れあり"},{id: 6, name: "全体的に状態が悪い"}
  ]
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/models/delivery_fee.rb
class DeliveryFee < ActiveHash::Base
  self.data = [
    {id: 1, name: '送料込み'},{id: 2, name: '着払い'}
  ]
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :user
    belongs_to :category
    belongs_to :size, optional: true
    belongs_to_active_hash :brand
    belongs_to_active_hash :ship_from_area
    belongs_to_active_hash :shipping_method
    belongs_to_active_hash :shipping_day
    belongs_to_active_hash :delivery_fee
    belongs_to_active_hash :condition
    has_many :images, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    has_one :order
  
    validates_associated :images
    validates :images, presence: true
    validates :name,
      presence: true,
      length: {maximum:40}
    validates :description,
      presence: true,
      length: {maximum:1000}
    validates :price,
      presence: true,
      numericality: {greater_than_or_equal_to:300,less_than:10000000}

    accepts_nested_attributes_for :images, allow_destroy:true

    def like_user(user_id)
      likes.find_by(user_id: user_id)
    end

    def self.search(search)
      Item.where(['name LIKE ?', "%#{search}%"])
    end

end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :item, counter_cache: :likes_count
  validates_uniqueness_of :item_id, scope: :user_id
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :item
  belongs_to :seller, class_name: 'User', optional: true, foreign_key: true
  belongs_to :buyer, class_name: 'User', optional: true, foreign_key: true

  validates :receiver_last_name, presence: true
  validates :receiver_first_name, presence: true
  validates :zipcode, presence: true
  validates :prefecture, presence: true
  validates :city, presence: true
  validates :address, presence: true
end

app/models/shipping_day.rb
class ShippingDay < ActiveHash::Base
  self.data = [
    {id: 1, name: '１〜2日で発送'},{id: 2, name: '2〜3日で発送'},{id: 3, name: '4〜7日で発送'}
  ]
end

app/models/shop.rb
class Shop < ApplicationRecord
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :items
  has_many :category_sizes
  has_many :categories, through: :category_sizes
  has_ancestry
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  validates :nickname, presence: true
  validates :last_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :birth_day, presence: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }, length: { minimum: 7 }
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true

  has_many :sns_credentials
  has_one :shipping_address
  has_many :items, dependent: :destroy
  has_one :credit_card
  has_many :order
  has_many :likes, dependent: :destroy
  has_many :liked_items, through: :likes, source: :item
  has_many :comments, dependent: :destroy

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_bread-crumbs.html.haml
.bread-crumb
  %ul.bread-crumb__nav
    %li.bread-crumb__nav__item
      = breadcrumbs separator: '&rsaquo;', class:"bread-crumbs"

app/views/layouts/_form_footer.html.haml
%ul.terms-lists
  %li.terms-lists__all
    = link_to "プライバシーポリシー","#",id:"policy"
  %li.terms-lists__all
    = link_to "フリマ利用規約","#",id:"furima-terms"
  %li.terms-lists__all
    = link_to "特定商取引に関する表記","#",id:"dealing"
= link_to image_tag("/images/logo-white.png",alt:"FURIMA",class:"logo-bottom",height:"65",width:"80"),"#", class:"bottom-logo"
%p.company-signature
  © Furima, Inc.

app/views/layouts/_main-footer.html.haml
%ul.contents-container
  %li.contents-container__lists
    %h2.contents-head
      FURIMAについて
    %ul.contents-list
      %li.contents-list__each
        = link_to "会社概要（運営会社）","#",class:"company-sammary"
      %li.contents-list__each
        = link_to "プライバシーポリシー","#",class:"company-sammary"
      %li.contents-list__each
        = link_to "FURIMA利用規約","#",class:"company-sammary"
      %li.contents-list__each
        = link_to "ポイントに関する特約","#",class:"company-sammary"
  %li.contents-container__lists
    %h2.contents-head
      FURIMAを見る
    %ul.contents-list
      %li.contents-list__each
        = link_to "カテゴリー一覧","#",class:"company-sammary"
      %li.contents-list__each
        = link_to "ブランド一覧","#",class:"company-sammary"
  %li.contents-container__lists
    %h2.contents-head
      ヘルプ&ガイド
    %ul.contents-list
      %li.contents-list__each
        = link_to "FURIMAガイド","#",class:"company-sammary"
      %li.contents-list__each
        = link_to "FURIMAロゴ利用ガイドライン","#",class:"company-sammary"
      %li.contents-list__each
        = link_to "お知らせ","#",class:"company-sammary"
.logo-container
  = link_to image_tag("/images/logo-white.png",alt:"FURIMA", class:"logo-image"), root_path, class:"logo-container__link"
%p.bottom-web-name
  ©︎　FURIMA

app/views/layouts/_main_header.html.haml
.header-inner
  .header-upper
    .logo-box
      =link_to image_tag("/images/logo.png", alt:"FURIMA", class: "logo-main"), root_path, class: "logo-header"
    .form-box
      = form_with(url: search_items_path,local: true,method: :get, class:"search-form") do |f|
        = f.text_field :search,class: "item-search", placeholder: "キーワードから探す"
        = button_tag(type: :submit,class:"search") do
          = image_tag("/images/icon-search1.png", alt: "search", class: "search-icon")
  .header-navigation-bar
    .navigation-left
      .navigation-category__categories
        %h2.category-title-box
          = link_to categories_path, class: "category" do
            %span.category-title__title
              カテゴリー
        %ul.categories-container
          - @category_parents.each do |parent|
            %li.categories-container__parent
              %h3.category-name
                = link_to "#{parent.name}",category_path(parent), class: "category-parent"
              %ul.categories-container-child
                - parent.children.each do |child|
                  %li.categories-container-child__child
                    %h3.category-name
                      = link_to "#{child.name}", category_path(child), class: "category-child"
                    %ul.categories-container-grandchild
                      - child.children.each do |grandchild|
                        %li.categories-container-grandchild__grandchild
                          %h3.category-name
                            = link_to "#{grandchild.name}", category_path(grandchild), class: "category-grandchild"
      .navigation-category__brands
        %h2.brand-title-box
          = link_to brands_path, class: "brand" do
            %span.brand-title__title
              ブランド
        %ul.brands-container
          - @brands[0...5].each do |brand|
            %li.brands-container__brand
              %h3.brand-name
                = link_to "#{brand.name}", brand_path(brand.id), class: "brand"
          %li.brands-container__brand
            %h3.brand-name
              = link_to "ブランド一覧", brands_path, class: "brand"
    .navigation-right
      - if user_signed_in?
        %ul.navigation-likes-mypage
          %li.navigation-likes-mypage__likes
            = link_to items_path, class: "likes-link" do
              = icon("fas", "store-alt")
              %span.navigation-likes-mypage__likes--title
                商品一覧
          %li.navigation-likes-mypage__likes
            = link_to likes_users_path, class: "likes-link" do
              = icon("far", "heart")
              %span.navigation-likes-mypage__likes--title
                いいね！一覧
          %li.navigation-likes-mypage__mypage
            = link_to user_path(current_user.id), class: "mypage-link" do
              = image_tag("/images/member_photo_noimage_thumb.png", alt: "mypage", class: "mypage")
              %span.navigation-likes-mypage__mypage--title
                マイページ
      - else
        %ul.navigation-login-signup
          %li.navigation-login-signup__product-list
            = link_to "商品一覧", items_path, class: "product-list-link"
          %li.navigation-login-signup__login
            = link_to "ログイン", new_user_session_path, class:"login"
          %li.navigation-login-signup__signup
            = link_to "新規会員登録", new_user_registration_path, class:"signup"

app/views/layouts/_main_pickup-items.html.haml
- @items.each do |item|
  .pickup-list
    = link_to item_path(item.id),class:"pickup" do
      .pickup-image
        = image_tag item.images[0].image.url,class:"image-pickup"
      .pickup-description
        %h3.name
          = item.name.truncate(12)
        .detail
          %ul.details
            %li.details__left
              = number_to_currency(item.price,format: "%u%n",unit: "¥")
            %li.details__right
              = icon("fas","star")
              %span.star-number
                0
        %p.tax
          (税込)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content:"text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title FreemarketSample71c
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    %link{ rel: "stylesheet", type: "text/css", href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"}
    %link{ rel: "stylesheet", type: "text/css", href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"}
    = javascript_include_tag 'application'
    %script{ type: "text/javascript", src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"}
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
  %body
    .notifications
      - flash.each do |key, value|
        = content_tag(:div, value, class:key)
    = yield